### ISSUE TITLE
error rwb.logviewer to open file in windows

### ISSUE THREAD

**Issue by ghost** [boakley/robotframework-workbench#11]
c:\Python27>python -m rwb.logviewer 
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Python27\lib\lib-tk\Tkinter.py", line 1410, in **call**
    return self.func(_args)
  File "c:\Python27\lib\site-packages\robotframework_workbench-0.4.0-py2.7.egg\rwb\logviewer\app.py"
, line 167, in _on_open
    title="Open")
  File "c:\Python27\lib\lib-tk\tkFileDialog.py", line 125, in askopenfilename
    return Open(_*options).show()
  File "c:\Python27\lib\lib-tk\tkCommonDialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
TclError: bad window path name "<rwb.logviewer.app.LogViewerApp object at 0x03053130>"

**Comment by boakley** [comment]
This is fixed in version 0.5. At some point in the past I split AbstractRwbApp into a non-GUI and GUI variety; when I did that, the GUIs **str** method started returning the wrong thing. This caused problems when Tkinter would try to convert a widget to it's internal name used by tk.
