### ISSUE TITLE
Save and Save as.. cause a traceback for new files

### ISSUE THREAD

**Issue by jussimalinen** [boakley/robotframework-workbench#7]
OSX 10.7.4, python 2.7.1, robot 2.6.3

start with "python -m rwb.editor"
1. Choose File->New
2. Edit test
3. Press cmd-s (or save or save as from menu)
   a traceback is printed on console

Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1410, in **call**
    return self.func(_args)
  File "rwb/editor/app.py", line 342, in _on_save
    self._on_save_as(event)
  File "rwb/editor/app.py", line 334, in _on_save_as
    title="Save As...")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/tkFileDialog.py", line 130, in asksaveasfilename
    return SaveAs(_*options).show()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/tkCommonDialog.py", line 48, in show
    s = w.tk.call(self.command, *w._options(self.options))
TclError: bad window path name "<rwb.editor.app.EditorApp object at 0x10ece0110>"

as a side note the step 1 also causes a traceback, but the editor still works after that:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 1410, in **call**
    return self.func(_args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk/Tkinter.py", line 495, in callit
    func(_args)
  File "rwb/editor/editor_page.py", line 356, in load
    raise Exception("nothing to load")
Exception: nothing to load

**Comment by boakley** [comment]
Thanks for the info. Instead of doing file-> new, if you do "python -m rwb.editor newfile.txt", are you able to save?

--bryan

**Comment by jussimalinen** [comment]
Yes I am. No problems then.
